"""fresh_init

Revision ID: 97dc65871249
Revises: 
Create Date: 2025-12-01 10:21:03.298591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dc65871249'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('file_number', sa.String(), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('tan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('cin', sa.String(), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin'),
    sa.UniqueConstraint('legal_name')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('statement_type', sa.String(), nullable=False),
    sa.Column('applicable_client_types', sa.Text(), nullable=True),
    sa.Column('template_definition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('financial_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('signing_date', sa.Date(), nullable=True),
    sa.Column('udin_number', sa.String(), nullable=True),
    sa.Column('udin_certificate_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_works_id'), ['id'], unique=False)

    op.create_table('signatories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('din_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('id_proof_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signatories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signatories_id'), ['id'], unique=False)

    op.create_table('user_company_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('work_report_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_work_id', sa.Integer(), nullable=False),
    sa.Column('custom_notes', sa.Text(), nullable=True),
    sa.Column('selected_signatories', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['financial_work_id'], ['financial_works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_work_id')
    )
    with op.batch_alter_table('work_report_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_report_configurations_id'), ['id'], unique=False)

    op.create_table('work_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_work_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['financial_work_id'], ['financial_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_units_id'), ['id'], unique=False)

    op.create_table('trial_balance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trial_balance_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_balance_entries_id'), ['id'], unique=False)

    op.create_table('mapped_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_balance_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_sub_head_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_sub_head_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['trial_balance_entry_id'], ['trial_balance_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_balance_entry_id')
    )
    with op.batch_alter_table('mapped_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapped_ledger_entries_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapped_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapped_ledger_entries_id'))

    op.drop_table('mapped_ledger_entries')
    with op.batch_alter_table('trial_balance_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_balance_entries_id'))

    op.drop_table('trial_balance_entries')
    with op.batch_alter_table('work_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_units_id'))

    op.drop_table('work_units')
    with op.batch_alter_table('work_report_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_report_configurations_id'))

    op.drop_table('work_report_configurations')
    op.drop_table('user_company_association')
    with op.batch_alter_table('signatories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signatories_id'))

    op.drop_table('signatories')
    with op.batch_alter_table('financial_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_works_id'))

    op.drop_table('financial_works')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_id'))

    op.drop_table('report_templates')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
