"""compliance_blocks

Revision ID: a01fd80fff1f
Revises: c815a447aeca
Create Date: 2025-12-02 12:42:43.418631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01fd80fff1f'
down_revision: Union[str, Sequence[str], None] = 'c815a447aeca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_definition', sa.Text(), nullable=True))
        batch_op.alter_column('content_html',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_templates', schema=None) as batch_op:
        batch_op.alter_column('content_html',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('template_definition')

    # ### end Alembic commands ###
