"""compliance_schema

Revision ID: a972e7d9c5db
Revises: 97dc65871249
Create Date: 2025-12-01 11:51:13.495866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a972e7d9c5db'
down_revision: Union[str, Sequence[str], None] = '97dc65871249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_templates_id'), ['id'], unique=False)

    op.create_table('organization_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_name', sa.String(), nullable=False),
    sa.Column('firm_registration_number', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_settings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_settings_id'))

    op.drop_table('organization_settings')
    with op.batch_alter_table('compliance_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_templates_id'))

    op.drop_table('compliance_templates')
    # ### end Alembic commands ###
