"""init_schema

Revision ID: c22588e89462
Revises: 
Create Date: 2025-11-27 17:46:39.392335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22588e89462'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('cin', sa.String(), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin'),
    sa.UniqueConstraint('legal_name')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('statement_type', sa.String(), nullable=False),
    sa.Column('template_definition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_table('financial_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_works_id'), 'financial_works', ['id'], unique=False)
    op.create_table('trial_balance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_work_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['financial_work_id'], ['financial_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_balance_entries_id'), 'trial_balance_entries', ['id'], unique=False)
    op.create_table('mapped_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_balance_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_sub_head_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_sub_head_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['trial_balance_entry_id'], ['trial_balance_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_balance_entry_id')
    )
    op.create_index(op.f('ix_mapped_ledger_entries_id'), 'mapped_ledger_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapped_ledger_entries_id'), table_name='mapped_ledger_entries')
    op.drop_table('mapped_ledger_entries')
    op.drop_index(op.f('ix_trial_balance_entries_id'), table_name='trial_balance_entries')
    op.drop_table('trial_balance_entries')
    op.drop_index(op.f('ix_financial_works_id'), table_name='financial_works')
    op.drop_table('financial_works')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
